apiVersion: v1
kind: ConfigMap
metadata:
  name: agp-configmap-default
data:
  server.port: 8089
  agp.host: 0.0.0.0
  
  vp.host: ind-dtjp-vp-vip
  vp.port: 8080
  
  ei.host: ind-dtjp-ei-vip
  ei.port: 8082
  
  tak.host: ind-dtjp-tomcat-vip
  tak.port: 8085
  
  # Installation basepath
  base.path: /opt/agp
  
  # Hawtio
  hawtio.authenticationEnabled: false
  
  # Camel spring-boot configurations
  camel.springboot.message-history: false
  camel.springboot.tracing: false
  
  # Total timeout for aggregated calls to producers
  aggregate.timeout: 28000
  
  # Outpoing parameters for calling services
  vp.instanceId: NTjP_T_SERVICES_SE165565594230-10BR
  vp.defaultReceiveTimeout: 27000
  vp.defaultConnectTimeout: 2000
  vp.defaultServiceURL: http://${vp.host}:${vp.port}/vp
  vp.useAyncHttpConduit: true
  
  # Outgoing parameters for calling EI-FindContent
  ei.logicalAddress: 5565594230
  ei.senderId: T_SERVICES_SE165565594230-10BR
  ei.findContentUrl: http://${ei.host}:${ei.port}/skltp-ei/find-content-service/v1
  ei.connectTimeout: 2000
  ei.receiveTimeout: 20000
  ei.useAyncHttpConduit: true
  
  # Other services URLs
  reset.cache.url: http://${agp.host}:8091/resetcache
  agp.status.url: http://${agp.host}:8080/status
  
  #Takcache configuration
  takcache.use.behorighet.cache: true
  takcache.use.vagval.cache: false
  takcache.persistent.file.name: ${base.path}/localCache
  takcache.endpoint.address: http://${tak.host}:${tak.port}/tak-services/SokVagvalsInfo/v2
  
  # Max size of payload loggings
  log.max.payload.size: 49152
  
  # Service special configuration
  getaggregatedrequestactivities.v1.receiveTimeout: 15000
  getaggregatedrequestactivities.v2.receiveTimeout: 15000
  getaggregatedsubjectofcareschedule.v1.receiveTimeout: 15000