apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aggServices.name }}
spec:
  selector:
    app.kubernetes.io/name: agp
  type: ClusterIP
  ports:
    {{- range $.Values.aggServices.ports }}
    - port: {{ . }}
      targetPort: aggservices
      protocol: TCP
      name: aggServices-{{ . }}
    {{- end }}

status:
  loadBalancer: {}
