repository: docker.drift.inera.se/ntjp/

deployment:
  replicaCount: 1
  elasticGrokFilter: camel

skltp:
  instanceId: SKLTP-DEFAULT-ID

# Environment-specific backwards-compatible service name
vip:
  name: default-ei-vip

aggServices:
  ports:
    - 9001

environment:
  variables:
    _default_config_maps:
      - agp-configmap-default
    config_maps:
    # Override to supply your own maps.
    secrets:
    # Override to supply your own secrets.
