container:
  repository: docker.drift.inera.se/ntjp/

aggServices:
  name: ind-dtjp-agp-vip
  ports:
    - 9001
    - 9002
    - 9003
    - 9004
    - 9005
    - 9006
    - 9007
    - 9008
    - 9010
    - 9011
    - 9012
    - 9013
    - 9014
    - 9015
    - 9016
    - 9018
    - 9019
    - 9020
    - 9021
    - 9024
    - 9026
    - 9027
    - 9028

environment:
  variables:
    _default_config_maps:
      - agp-configmap-default
    config_maps:
    # Override to supply your own maps.
    secrets:
    # Override to supply your own secrets.
