repository: docker.drift.inera.se/ntjp/

deployment:
  replicaCount: 1
  imagePullPolicy: Always
  elasticGrokFilter: camel
  resources: {} # Override to specify resources
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: agp
      maxSkew: 2
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway

skltp:
  instanceId: SKLTP-DEFAULT-ID

# Environment-specific backwards-compatible service name
vip:
  name: default-ei-vip

aggServices:
  ports:
    - 9001

environment:
  variables:
    _default_config_maps:
      - agp-configmap-default
    config_maps:
    # Override to supply your own maps.
    secrets:
    # Override to supply your own secrets.

log4j:
  loggers:
    - name: se.skltp.aggregatingservices
      level: INFO
    - name: se.skltp.takcache
      level: INFO
    - name: se.skltp.aggregatingservices.logging
      level: INFO
    - name: se.skltp.aggregatingservices.logging.FindContentResponderInterface
      level: DEBUG
  rootLoggerLevel: WARN

probes:
  startupProbe:
    httpGet:
      path: actuator/health/readiness
      port: 8089
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 5  # 30s initial + 18 failures * 5s period = 120 seconds max startup before failure and restart.
    timeoutSeconds: 4
    successThreshold: 1
    failureThreshold: 18
  livenessProbe:
    httpGet:
      path: actuator/health/liveness
      port: 8089
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    # 3x 10s + 5s timeout allows for up to 45 seconds of non-responsiveness before pod kill-and-restart.
    #    Earliest kill possible 55 seconds after startup completes.
    failureThreshold: 4
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: actuator/health/readiness
      port: 8089
      scheme: HTTP
    # lower initial delay than liveness, but same period, allows traffic to be governed before liveness is tested.
    initialDelaySeconds: 9
    periodSeconds: 10
    timeoutSeconds: 5
    # 1x 10s + timeout 5s allows for up to 15 seconds on non-response before traffic is cut from pod.
    #    Earliest cut possible 24 seconds after startup completes.
    failureThreshold: 1
    successThreshold: 1


