repository: docker.drift.inera.se/ntjp/

skltp:
  instanceId: SKLTP-DEFAULT-ID

aggServices:
  name: agp-services
  ports:
    - 9001

environment:
  variables:
    _default_config_maps:
      - agp-configmap-default
    config_maps:
    # Override to supply your own maps.
    secrets:
    # Override to supply your own secrets.
